// SPIKE: the words code is heard as, for gen.mjs. Each line is a Concept of the code-hearing
// pack: what it is (its kinds), how it is spelled when it is a symbol, and how tightly it binds
// (higher is tighter). A relation that holds only in one language says so.
export const TS = "Code(TypeScript())";
export const PY = "Code(Python())";
const only = (claim, lang) => `Relation(${claim}, context = ${lang})`;

// [head, kinds, spelled, binds, extra relations]
export const WORDS = [
  // Operators between two things.
  ["Dot", ["Infix"], ".", "Binds(200)"],
  ["OptionalDot", ["Infix"], "?.", "Binds(200)"],
  ["Power", ["Infix"], "**", "Binds(140, Right())"],
  ["Times", ["Infix"], "*", "Binds(120)"],
  ["Over", ["Infix"], "/", "Binds(120)"],
  ["Modulo", ["Infix"], "%", "Binds(120)"],
  ["Plus", ["Infix", "Unary"], "+", "Binds(110)"],
  ["Minus", ["Infix", "Unary"], "-", "Binds(110)"],
  ["Greater", ["Infix"], ">", "Binds(90)", ["SynonymOf(GreaterThan())"]],
  ["Less", ["Infix"], "<", "Binds(90)", ["SynonymOf(LessThan())"]],
  ["AtLeast", ["Infix"], ">=", "Binds(90)"],
  ["AtMost", ["Infix"], "<=", "Binds(90)"],
  ["In", ["Infix"], undefined, "Binds(90)"],
  ["Instanceof", ["Infix"], undefined, "Binds(90)", ["SynonymOf(InstanceOf())"], TS],
  ["As", ["Infix"], undefined, "Binds(90)"],
  ["Satisfies", ["Infix"], undefined, "Binds(90)", TS],
  ["Is", ["Infix"], undefined, "Binds(90)", PY],
  ["Equals", ["Infix"], "===", "Binds(80)", [only('Spelled("==")', PY)]],
  ["NotEquals", ["Infix"], "!==", "Binds(80)", [only('Spelled("!=")', PY)]],
  ["LooseEquals", ["Infix"], undefined, "Binds(80)", [only('Spelled("==")', TS)], TS],
  ["LooseNotEquals", ["Infix"], undefined, "Binds(80)", [only('Spelled("!=")', TS)], TS],
  ["Ampersand", ["Infix"], "&", "Binds(70)", ["SynonymOf(BitAnd())"]],
  ["Caret", ["Infix"], "^", "Binds(60)", ["SynonymOf(BitXor())"]],
  ["Bar", ["Infix"], "|", "Binds(50)", ["SynonymOf(BitOr())"]],
  ["And", ["Infix"], "&&", "Binds(40)"],
  ["Or", ["Infix"], "||", "Binds(30)"],
  ["Otherwise", ["Infix"], "??", "Binds(30)"],
  ["Of", ["Infix"], undefined, "Binds(22)", TS],
  ["Assign", ["Infix"], "=", "Binds(20, Right())"],
  ["PlusAssign", ["Infix"], "+=", "Binds(20, Right())"],
  ["MinusAssign", ["Infix"], "-=", "Binds(20, Right())"],
  ["TimesAssign", ["Infix"], "*=", "Binds(20, Right())"],
  ["OrAssign", ["Infix"], "||=", "Binds(20, Right())"],
  ["AndAssign", ["Infix"], "&&=", "Binds(20, Right())"],
  ["OtherwiseAssign", ["Infix"], "??=", "Binds(20, Right())"],
  ["Arrow", ["Infix", "TakesBlock"], "=>", "Binds(20, Right())", TS],
  ["Colon", ["Infix"], ":", "Binds(15)"],
  ["OptionalColon", ["Infix"], "?:", "Binds(15)", TS],
  ["Returns", ["Infix"], undefined, "Binds(25)", TS],
  ["From", ["Infix"], undefined, "Binds(10)", [only("IsA(Prefix())", PY), only("Binds(0)", PY)]],
  ["Extends", ["Infix"], undefined, "Binds(10)", TS],
  ["Implements", ["Infix"], undefined, "Binds(10)", TS],
  ["Increment", ["Infix", "Unary"], "++", "Binds(160)", TS],
  ["Decrement", ["Infix", "Unary"], "--", "Binds(160)", TS],
  // Words that lead: each takes what follows it, as far as its Binds lets it.
  ["Not", ["Infix", "Prefix", "Unary"], "!", "Binds(150)", [only("Binds(60)", PY)]],
  ["Typeof", ["Prefix"], undefined, "Binds(150)", ["SynonymOf(TypeOf())"], TS],
  ["Await", ["Prefix"], undefined, "Binds(150)"],
  ["Void", ["Prefix"], undefined, "Binds(150)", TS],
  ["Delete", ["Prefix"], undefined, "Binds(150)", TS],
  ["New", ["Prefix"], undefined, "Binds(190)", TS],
  ["Spread", ["Prefix"], "...", "Binds(20)", TS],
  ["Const", ["Prefix"], undefined, "Binds(180)", TS],
  ["Let", ["Prefix"], undefined, "Binds(180)", TS],
  ["Var", ["Prefix"], undefined, "Binds(180)", TS],
  ["Async", ["Prefix"], undefined, "Binds(180)"],
  ["Static", ["Prefix"], undefined, "Binds(180)", TS],
  ["Readonly", ["Prefix"], undefined, "Binds(180)", TS],
  ["Private", ["Prefix"], undefined, "Binds(180)", TS],
  ["Public", ["Prefix"], undefined, "Binds(180)", TS],
  ["Protected", ["Prefix"], undefined, "Binds(180)", TS],
  ["Abstract", ["Prefix"], undefined, "Binds(180)", TS],
  ["Declare", ["Prefix"], undefined, "Binds(180)", TS],
  ["Get", ["Prefix"], undefined, "Binds(180)", TS],
  ["Set", ["Prefix"], undefined, "Binds(180)", TS],
  ["Return", ["Prefix"], undefined, "Binds(0)"],
  ["Throw", ["Prefix"], undefined, "Binds(0)", TS],
  ["Raise", ["Prefix"], undefined, "Binds(0)", PY],
  ["Yield", ["Prefix"], undefined, "Binds(0)"],
  ["Break", ["Prefix"], undefined, "Binds(0)"],
  ["Continue", ["Prefix"], undefined, "Binds(0)"],
  ["Import", ["Prefix", "Callable"], undefined, "Binds(0)", [only("IsA(Infix())", PY), only("Binds(10)", PY)]],
  ["Export", ["Prefix"], undefined, "Binds(0)", TS],
  ["Default", ["Prefix"], undefined, "Binds(0)", TS],
  ["Type", ["Prefix"], undefined, "Binds(0)", TS],
  ["Interface", ["Prefix"], undefined, "Binds(0)", TS],
  ["Enum", ["Prefix"], undefined, "Binds(0)", TS],
  ["Namespace", ["Prefix"], undefined, "Binds(0)", TS],
  ["Class", ["Prefix"], undefined, "Binds(0)"],
  ["Function", ["Prefix"], undefined, "Binds(0)", TS],
  ["Def", ["Prefix"], undefined, "Binds(0)", PY],
  ["Lambda", ["Prefix"], undefined, "Binds(20)", PY],
  ["With", ["Prefix"], undefined, "Binds(0)", PY],
  ["Assert", ["Prefix"], undefined, "Binds(0)", PY],
  ["Global", ["Prefix"], undefined, "Binds(0)", PY],
  ["Del", ["Prefix"], undefined, "Binds(0)", PY],
  ["Try", ["Prefix", "TakesBlock"], undefined, "Binds(0)"],
  ["Do", ["Prefix", "TakesBlock"], undefined, "Binds(0)", TS],
  ["If", ["Prefix", "Heads"], undefined, "Binds(0)"],
  ["For", ["Prefix", "Heads"], undefined, "Binds(0)"],
  ["While", ["Prefix", "Heads"], undefined, "Binds(0)"],
  ["Switch", ["Prefix", "Heads"], undefined, "Binds(0)", TS],
  // Words that go on from the statement before them.
  ["Else", ["Continues", "TakesBlock"], undefined, "Binds(0)"],
  ["Elif", ["Continues"], undefined, "Binds(0)", PY],
  ["Catch", ["Continues", "Heads"], undefined, "Binds(0)", TS],
  ["Except", ["Continues"], undefined, "Binds(0)", PY],
  ["Finally", ["Continues", "TakesBlock"], undefined, "Binds(0)", TS],
  // Brackets.
  ["Parens", ["Opener", "Round"], "("],
  ["Brackets", ["Opener"], "["],
  ["Braces", ["Opener"], "{"],
  ["Block", ["Scope"]],
  ["Indent", ["Scope"]],
  ["Index", ["Opener", "Postfix"], undefined, "Binds(200)"],
  ["Angles", ["Opener", "Attached"], undefined, undefined, ["ClosedBy(AngleEnd())"]],
  ["Template", ["Opener", "Juxtaposed"], undefined, undefined, ["ClosedBy(TemplateEnd())"]],
  ["Interpolation", ["Opener", "Transparent"], "${"],
  ["Question", ["Opener", "Infix"], "?", "Binds(25, Right())", ["ClosedBy(Colon())"], TS],
  ["CloseParen", ["Closer"], ")"],
  ["CloseBracket", ["Closer"], "]"],
  ["CloseBrace", ["Closer"], "}"],
  ["Dedent", ["Closer"]],
  ["AngleEnd", ["Closer"]],
  ["TemplateEnd", ["Closer"]],
  // Separators and layout.
  ["Comma", ["Separator"], ","],
  ["Semicolon", ["Separator"], ";"],
  ["Newline", ["Separator"]],
];
